---
title: ''
mainfont: Arial
fontsize: 12pt
documentclass: report
header-includes:
- \PassOptionsToPackage{table}{xcolor}
- \usepackage{caption}
- \usepackage{amssymb}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage[table]{xcolor}
- \usepackage{fancyhdr}
- \usepackage{boldline}
- \usepackage{tipa}
   \definecolor{headergrey}{HTML}{545454}
   \definecolor{msdblue}{HTML}{1C93D1}
   \pagestyle{fancy}
   \setlength\headheight{30pt}
   \rhead{\color{headergrey}\today}
   \fancyhead[L]{\color{headergrey}Moretz, Brandon}
   \fancyhead[C]{\Large\bfseries\color{headergrey}Normal Linear Models}
   \rfoot{\color{headergrey}Chapter 4}
   \lfoot{\color{headergrey}}
   \fancyfoot[C]{\rmfamily\color{headergrey}Bayesian Data Analysis}
geometry: left = 1cm, right = 1cm, top = 2cm, bottom = 3cm
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    fig_caption: yes
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
---


```{r knitr_setup, include = FALSE}

knitr::opts_chunk$set(
   echo = T, 
   eval = TRUE, 
   dev = 'png', 
   fig.width = 9, 
   fig.height = 4.5)

options(knitr.table.format = "latex")

```

```{r report_setup, message = FALSE, warning = FALSE, include = FALSE}

library(data.table, quietly = TRUE, warn.conflicts = FALSE)
library(dplyr, quietly = TRUE, warn.conflicts = FALSE)
library(ggthemes, quietly = TRUE, warn.conflicts = FALSE)
library(scales, quietly = TRUE, warn.conflicts = FALSE)
library(cowplot, quietly = TRUE, warn.conflicts = FALSE)
library(GGally, quietly = TRUE, warn.conflicts = FALSE)

library(knitr, quietly = TRUE, warn.conflicts = FALSE)
library(kableExtra, quietly = TRUE, warn.conflicts = FALSE)
library(pander, quietly = TRUE, warn.conflicts = FALSE)
library(formattable, quietly = TRUE, warn.conflicts = FALSE)

library(grid, quietly = TRUE, warn.conflicts = FALSE)
library(gridExtra, quietly = TRUE, warn.conflicts = FALSE)
library(extrafont, quietly = TRUE, warn.conflicts = FALSE)
library(tinytex, quietly = TRUE, warn.conflicts = FALSE)

library(here, quietly = TRUE, warn.conflicts = FALSE)

library(lattice, quietly = TRUE, warn.conflicts = FALSE)

library(blmeco, quietly = TRUE, warn.conflicts = FALSE)
library(tidybayes, quietly = TRUE, warn.conflicts = FALSE)
library(arm, quietly = TRUE, warn.conflicts = FALSE)
library(coda, quietly = TRUE, warn.conflicts = FALSE)

options(tinytex.verbose = TRUE)
suppressMessages(library("tidyverse"))

pretty_kable <- function(data, title, dig = 2) {
  kable(data, caption = title, digits = dig) %>%
    kable_styling(bootstrap_options = c("striped", "hover")) %>%
      kableExtra::kable_styling(latex_options = "hold_position")
}

theme_set(theme_light())

# Theme Overrides
theme_update(axis.text.x = element_text(size = 10),
             axis.text.y = element_text(size = 10),
             plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "darkgreen"),
             axis.title = element_text(face = "bold", size = 12, colour = "steelblue4"),
             plot.subtitle = element_text(face = "bold", size = 8, colour = "darkred"),
             legend.title = element_text(size = 12, color = "darkred", face = "bold"),
             legend.position = "right", legend.title.align=0.5,
             panel.border = element_rect(linetype = "solid", 
                                         colour = "lightgray"), 
             plot.margin = unit(c( 0.1, 0.1, 0.1, 0.1), "inches"))

```

```{r pander_setup, include = FALSE}

knitr::opts_chunk$set(comment = NA)

panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)

```

# Normal Linear Models

## Fitting a Linear Regression in R

```{r}
n <- 50 # sample size
sigma <- 5 # standard deviation of the residuals
b0 <- 2 # intercept
b1 <- 0.7 # slope
x <- runif(n, 10, 30) # sample values of the covariate
yhat <- b0 + b1*x
y <- rnorm(n, yhat, sd=sigma)

# plot the data
plot(x, y, pch=16, las=1, cex.lab=1.2)
abline(lm(y~x), lwd=2, col="blue") # insert regression line
# add residuals
segments(x, fitted(lm(y~x)), x, y, lwd=2, col="orange", lty=3)
```

Fit the model

```{r}
mod <- lm(y~x)
mod

summary(mod)

summary(mod)$sigma
```

### Drawing Conclusions

Alternative Display

```{r}
nsim <- 1000
bsim <- sim(mod, n.sim = nsim)

plot(x, y, pch=16, las=1, cex.lab=1.2)
for(i in 1:nsim) abline(coef(bsim)[i, 1], coef(bsim)[i, 2],
                        col = rgb(0, 0, 0, 0.05))

newdat <- data.frame(x = seq(10, 30, by=0.1))
newmodmat <- model.matrix(~x, data = newdat)
fitmat <- matrix(ncol = nsim, nrow = nrow(newdat))

for(i in 1:nsim) fitmat[, i] <- newmodmat %*% coef(bsim)[i, ]
plot(x, y, pch=16, las=1, cex.lab=1.2)
abline(mod, lwd=2)

lines(newdat$x, apply(fitmat, 1, quantile, prob = 0.025, lty=3))
lines(newdat$x, apply(fitmat, 1, quantile, prob=0.975, lty=3))
```

Predicting Future Observations

```{r}
plot(x, y, pch=16, las=1, cex.lab=1.2)

# prepare matrix for simulated new data
newy <- matrix(ncol = nsim, nrow = nrow(newdat))
# for each simulate4d fitted value, simulate  one new y-value
for(i in 1:nsim) newy[, i] <- rnorm(nrow(newdat), mean = fitmat[, i],
                                    sd = bsim@sigma[i])

lines(newdat$x, apply(newy, 1, quantile, prob=0.025), lty=3)
lines(newdat$x, apply(newy, 1, quantile, prob=0.975), lty=3)
```

```{r}
sum(newy[newdat$x == 25,] > 20) / nsim
```

### Frequentist Results

```{r}
summary(mod)
```

## Regression Variants: ANOVA, ANCOVA, and MLR

```{r}
# data simulation
mu <- 12
sigma <- 2
b1 <- 3
b2 <- -5
n <- 90
group <- factor(rep(c(1, 2, 3), each = 30))

# simulate the y variable
simresid <- rnorm(n, mean=0, sd=sigma)
y <- mu + as.numeric(group == 2) * b1 + as.numeric(group == "3") * b2 +
   simresid

```

```{r}
group <- factor(group) # define group as a factor
mod <- lm(y ~ group) # fit the model

mod

summary(mod)$sigma
```

```{r}
bsim <- sim(mod, n.sim=1000)
m.g1 <- coef(bsim)[, 1]
m.g2 <- coef(bsim)[, 1] + coef(bsim)[, 2]
m.g3 <- coef(bsim)[, 1] + coef(bsim)[, 3]

m.dat <- data.table(group1 = m.g1, group2 = m.g2, group3 = m.g3)
m.dat.long <- melt(m.dat)
m.dat.long[, Mean := mean(value), by = variable]

p1 <- ggplot(m.dat.long) +
   geom_density(aes(value, fill = variable), alpha = .6)

p2 <- ggplot(m.dat.long) +
   geom_point(aes(x = variable, y = Mean, color = variable), alpha = .75, size = 6)

grid.arrange(p1, p2, ncol=2)

d.g1.2 <- m.g1 - m.g2
mean(d.g1.2)
quantile(d.g1.2, prob=c(0.025, 0.975))

sum(m.g2 > m.g1) / nsim
```

## Frequentist Results

```{r}
data("periparusater")
dat <- periparusater

mod <- lm(wing ~ sex + age, data=dat)
plot(mod)

newdat <- expand.grid(sex = factor(c(1, 2)), age = factor(c(3, 4)))
newdat$fit <- model.matrix(~sex + age, dat=newdat) %*% coef(mod)

nsim <- 2000
bsim <- sim(mod, n.sim = nsim)

fitmat <- matrix(ncol = nsim, nrow = nrow(newdat))
Xmat <- model.matrix(formula(mod)[c(1,3)], dat = newdat)
for(i in 1:nsim) fitmat[, i] <- Xmat %*% bsim@coef[i, ]

alpha <- .05
intervals <- c(lower = alpha/2, upper = 1 - alpha/2)

ci <- t(apply(fitmat, 1, quantile, prob = intervals))

cbind(newdat, ci)

mod2 <- lm(wing ~ sex * age, data = dat)

```

```{r}
bsim2 <- sim(mod2, n.sim = nsim)
quantile(bsim2@coef[, 4], prob = c(0.025, 0.5, 0.975))

summary(mod2)$sigma

mean(abs(bsim2@coef[, 4]) > 0.3)

coef(mod2)

quantile(bsim2@coef[, 2], prob = c(0.025, 0.5, 0.975))      

sum(bsim@coef[, 2] < 0)/nsim # for juveniles (reference level)
sum(bsim@coef[, 2] + bsim2@coef[, 4] < 0) / nsim # adults

```

## Analysis of Covariance

```{r}
data("ellenberg")

index <- is.element(ellenberg$Species, c("Ap", "Dg"))
dat <- ellenberg[index, ] # select two species
dat <- droplevels(dat) # drop unused factor levels
str(dat) # definitions

mod <- lm(log(Yi.g) ~ Species + Water, data = dat)

head(model.matrix(mod)) # print the first 6 rows of the matrix

summary(mod)

mod2 <- lm(log(Yi.g) ~ Species*Water, data = dat)
summary(mod2)
```

```{r}
nsim <- 2000
bsim <- sim(mod2, n.sim = nsim)
coefs <- coef(bsim)

xatcross <- crosspoint(coefs[, 1], coefs[, 3],
                       coefs[, 1] + coefs[, 2], coefs[, 3] + coefs[, 4])[ , 1]

xatcross[xatcross< (-5)] <- -5

th <- hist(xatcross, breaksw = seq(-5.5, 140.5, by=5))
plot(th$mids, cumsum(th$counts)/2000, type = "l", lwd=2, las=1,
     ylim=c(0, 1), ylab="P(Dg > Ap|data)", xlab="Average diistance to ground water (cm)")
```

## Multiple Regression and Collinearity

```{r}
data(mdat)
mod <- lm(y ~ x1 + x2, data = mdat)
summary(mod)
```

```{r}
cor(mdat[, 2:6])

ggpairs(mdat)

own.graph <- function(x, y) {
   points(x, y, pch=16, col=rgb(1, 0.5, 0.0, 0.8))
   abline(lm(y~x))
}
pairs(mdat, panel = own.graph)
```

## Ordered Factors and Constants

```{r}
data("swallows")
levels(swallows$nesting_aid)

str(swallows)

contrasts(swallows$nesting_aid)

swallows$nesting_aid <- factor(swallows$nesting_aid, levels = 
                                  c("none", "support", "artif_nest", "both"),
                                  ordered = T)
levels(swallows$nesting_aid)

contrasts(swallows$nesting_aid)
```

