---
title: ''
mainfont: Arial
fontsize: 12pt
documentclass: report
header-includes:
- \PassOptionsToPackage{table}{xcolor}
- \usepackage{caption}
- \usepackage{amssymb}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage[table]{xcolor}
- \usepackage{fancyhdr}
- \usepackage{boldline}
- \usepackage{tipa}
   \definecolor{headergrey}{HTML}{545454}
   \definecolor{msdblue}{HTML}{1C93D1}
   \pagestyle{fancy}
   \setlength\headheight{30pt}
   \rhead{\color{headergrey}\today}
   \fancyhead[L]{\color{headergrey}Moretz, Brandon}
   \fancyhead[C]{\Large\bfseries\color{headergrey}Likelihood}
   \rfoot{\color{headergrey}Chapter 5}
   \lfoot{\color{headergrey}}
   \fancyfoot[C]{\rmfamily\color{headergrey}Bayesian Data Analysis}
geometry: left = 1cm, right = 1cm, top = 2cm, bottom = 3cm
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    fig_caption: yes
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
---


```{r knitr_setup, include = FALSE}

knitr::opts_chunk$set(
   echo = T, 
   eval = TRUE, 
   dev = 'png', 
   fig.width = 9, 
   fig.height = 4.5)

options(knitr.table.format = "latex")

```

```{r report_setup, message = FALSE, warning = FALSE, include = FALSE}

library(data.table, quietly = TRUE, warn.conflicts = FALSE)
library(dplyr, quietly = TRUE, warn.conflicts = FALSE)
library(ggthemes, quietly = TRUE, warn.conflicts = FALSE)
library(scales, quietly = TRUE, warn.conflicts = FALSE)
library(cowplot, quietly = TRUE, warn.conflicts = FALSE)
library(GGally, quietly = TRUE, warn.conflicts = FALSE)

library(knitr, quietly = TRUE, warn.conflicts = FALSE)
library(kableExtra, quietly = TRUE, warn.conflicts = FALSE)
library(pander, quietly = TRUE, warn.conflicts = FALSE)
library(formattable, quietly = TRUE, warn.conflicts = FALSE)

library(grid, quietly = TRUE, warn.conflicts = FALSE)
library(gridExtra, quietly = TRUE, warn.conflicts = FALSE)
library(extrafont, quietly = TRUE, warn.conflicts = FALSE)
library(tinytex, quietly = TRUE, warn.conflicts = FALSE)

library(here, quietly = TRUE, warn.conflicts = FALSE)

library(lattice, quietly = TRUE, warn.conflicts = FALSE)

library(blmeco, quietly = TRUE, warn.conflicts = FALSE)
library(tidybayes, quietly = TRUE, warn.conflicts = FALSE)
library(arm, quietly = TRUE, warn.conflicts = FALSE)
library(coda, quietly = TRUE, warn.conflicts = FALSE)

options(tinytex.verbose = TRUE)
suppressMessages(library("tidyverse"))

pretty_kable <- function(data, title, dig = 2) {
  kable(data, caption = title, digits = dig) %>%
    kable_styling(bootstrap_options = c("striped", "hover")) %>%
      kableExtra::kable_styling(latex_options = "hold_position")
}

theme_set(theme_light())

# Theme Overrides
theme_update(axis.text.x = element_text(size = 10),
             axis.text.y = element_text(size = 10),
             plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "darkgreen"),
             axis.title = element_text(face = "bold", size = 12, colour = "steelblue4"),
             plot.subtitle = element_text(face = "bold", size = 8, colour = "darkred"),
             legend.title = element_text(size = 12, color = "darkred", face = "bold"),
             legend.position = "right", legend.title.align=0.5,
             panel.border = element_rect(linetype = "solid", 
                                         colour = "lightgray"), 
             plot.margin = unit(c( 0.1, 0.1, 0.1, 0.1), "inches"))

```

```{r pander_setup, include = FALSE}

knitr::opts_chunk$set(comment = NA)

panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)

```

# Likelihood

## Theory

Given 3 observations .8, 1.2, 1.1 and a model $y_i \sim Norm(1, .2)$

```{r}
obs <- c(0.8, 1.2, 1.1) # observations

# probability of seeing  these  in n(1, .2)
p1 <- prod(dnorm(obs, mean = 1, sd = 0.2))
p1

# probability of seeing  these  in n(1.2, .4)
p2 <- prod(dnorm(obs, mean = 1.2, sd = 0.4))
p2

p1/p2 # 4x liklier to see under model 1 than model 2

# graphically
xs <- seq(from=0, to=3, by = .01)
ys <- dnorm(xs, mean = 1, sd = .2)

dat <- data.table(x = xs, y = ys)

obs_marks <- data.table(x = obs, y = dnorm(obs, mean = 1, sd = .2))

ggplot(dat) +
   geom_line(aes(x,y), col = "darkgreen", lty=2) +
   geom_hline(yintercept = 0) +
   geom_segment(data = obs_marks, aes(x, y, xend=x, yend=0), col="darkred")

```

## Quick Look at the Normal Distribution

```{r}
x <- seq(0, 2, length = 100)
dx <- dnorm(x, mean = 1, sd = 0.2)
plot(x, dx, type = "l", xlab = "Weight (kg)", ylab = "Density", lwd = 2, las = 1)

rnorm(5, 1, 0.2) # draws 5 random numbers from Norm(1, 0.2)

pnorm(q = .8, 1, 0.2)
```

$L(\mu, \sigma | y) = \prod^n_{i=1}p(y_i, |\mu, \sigma)$

```{r}
y <- c(0.8, 1.2, 1.1)
lf <- function(mu, sigma) prod(dnorm(y, mu, sigma))

lf(1, .2)
```

## The Maximum Likelihood Method

```{r}
mu <- seq(0.6, 1.4, length=100)
sigma <- seq(0.05, 0.6, length=100)

lik <- matrix(nrow=length(mu), ncol = length(sigma))

for(i in 1:length(mu)) {
   for(j in 1:length(sigma)) {
      lik[i, j] <- lf(mu[i], sigma[j])
   }
}

contour(mu, sigma, lik, nlevels=20, xlab = expression(mu),
        ylab =expression(sigma), las=1, cex.lab = 1.4)

neglf <- function(x) -prod(dnorm(y, x[1], x[2]))
MLest <- optim(c(1, 0.2), neglf)
MLest$par

# optimal values
points(MLest$par[1], MLest$par[2], col="red", pch=4)

```

Likelihood ratio = p1/p2

## The Log Pointwise Predictive Density

$llpd = \sum^n_{i=1}log\int{p(y_i|\theta)p(\theta|y)d\theta}$

```{r}

mod <- lm(y~1) # fit model by LS method
nsim <- 2000
bsim <- sim(mod, n.sim=nsim) # simulate from posterior dist. of parameters

pyi <- matrix(nrow=length(y), ncol=nsim)

for(i in 1:nsim) pyi[, i] <- dnorm(y, mean=bsim@coef[i, 1],
                              sd=bsim@sigma[i])

mpyi <- apply(pyi, 1, mean)

sum(log(mpyi))

```

The log posterior density can be used as a measure of model fit.
