---
title: ''
mainfont: Arial
fontsize: 12pt
documentclass: report
header-includes:
- \PassOptionsToPackage{table}{xcolor}
- \usepackage{caption}
- \usepackage{amssymb}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage[table]{xcolor}
- \usepackage{fancyhdr}
- \usepackage{boldline}
- \usepackage{tipa}
   \definecolor{headergrey}{HTML}{545454}
   \definecolor{msdblue}{HTML}{1C93D1}
   \pagestyle{fancy}
   \setlength\headheight{30pt}
   \rhead{\color{headergrey}\today}
   \fancyhead[L]{\color{headergrey}Moretz, Brandon}
   \fancyhead[C]{\Large\bfseries\color{headergrey}Assessing Model Assumptions}
   \rfoot{\color{headergrey}Chapter 5}
   \lfoot{\color{headergrey}}
   \fancyfoot[C]{\rmfamily\color{headergrey}Bayesian Data Analysis}
geometry: left = 1cm, right = 1cm, top = 2cm, bottom = 3cm
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    fig_caption: yes
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
---


```{r knitr_setup, include = FALSE}

knitr::opts_chunk$set(
   echo = T, 
   eval = TRUE, 
   dev = 'png', 
   fig.width = 9, 
   fig.height = 4.5)

options(knitr.table.format = "latex")

```

```{r report_setup, message = FALSE, warning = FALSE, include = FALSE}

library(data.table, quietly = TRUE, warn.conflicts = FALSE)
library(dplyr, quietly = TRUE, warn.conflicts = FALSE)
library(ggthemes, quietly = TRUE, warn.conflicts = FALSE)
library(scales, quietly = TRUE, warn.conflicts = FALSE)
library(cowplot, quietly = TRUE, warn.conflicts = FALSE)
library(GGally, quietly = TRUE, warn.conflicts = FALSE)

library(knitr, quietly = TRUE, warn.conflicts = FALSE)
library(kableExtra, quietly = TRUE, warn.conflicts = FALSE)
library(pander, quietly = TRUE, warn.conflicts = FALSE)
library(formattable, quietly = TRUE, warn.conflicts = FALSE)

library(grid, quietly = TRUE, warn.conflicts = FALSE)
library(gridExtra, quietly = TRUE, warn.conflicts = FALSE)
library(extrafont, quietly = TRUE, warn.conflicts = FALSE)
library(tinytex, quietly = TRUE, warn.conflicts = FALSE)

library(here, quietly = TRUE, warn.conflicts = FALSE)

library(lattice, quietly = TRUE, warn.conflicts = FALSE)

library(blmeco, quietly = TRUE, warn.conflicts = FALSE)
library(tidybayes, quietly = TRUE, warn.conflicts = FALSE)
library(arm, quietly = TRUE, warn.conflicts = FALSE)
library(coda, quietly = TRUE, warn.conflicts = FALSE)
library(nlme, quietly = TRUE, warn.conflicts = FALSE)
library(sp, quietly = TRUE, warn.conflicts = FALSE)
library(gstat, quietly = TRUE, warn.conflicts = FALSE)

options(tinytex.verbose = TRUE)
suppressMessages(library("tidyverse"))

pretty_kable <- function(data, title, dig = 2) {
  kable(data, caption = title, digits = dig) %>%
    kable_styling(bootstrap_options = c("striped", "hover")) %>%
      kableExtra::kable_styling(latex_options = "hold_position")
}

theme_set(theme_light())

# Theme Overrides
theme_update(axis.text.x = element_text(size = 10),
             axis.text.y = element_text(size = 10),
             plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "darkgreen"),
             axis.title = element_text(face = "bold", size = 12, colour = "steelblue4"),
             plot.subtitle = element_text(face = "bold", size = 8, colour = "darkred"),
             legend.title = element_text(size = 12, color = "darkred", face = "bold"),
             legend.position = "right", legend.title.align=0.5,
             panel.border = element_rect(linetype = "solid", 
                                         colour = "lightgray"), 
             plot.margin = unit(c( 0.1, 0.1, 0.1, 0.1), "inches"))

```

```{r pander_setup, include = FALSE}

knitr::opts_chunk$set(comment = NA)

panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)

```

# Assessing Model Assumptions

## Model Assumptions

```{r}

data("periparusater")

dat <- periparusater
mod <- lm(wing ~ sex + age, data = dat)
par(mfrow = c(2, 2))
plot(mod)

```

```{r}
names(dat)

plot(resid(mod) ~ country, data = dat)
plot(resid(mod) ~ age, data = dat)
plot(resid(mod) ~ sex, data = dat)
plot(resid(mod) ~ weight, data = dat)

```

```{r}
table(dat$country)

ggplot(dat, aes(y = country)) +
   geom_histogram(aes(fill = ..count..), stat = "count")

```

## The QQ

```{r}
compareqqnorm(mod)
```

## Temporal Autocorrelation

```{r}
data("parusmajor")

dat <- parusmajor
str(dat)

dat <- dat[order(dat$year, dat$julian), ] # order date acc, time
t.poly.jul <- poly(dat$julian, degree=2)
dat$julian.l <- t.poly.jul[, 1] # orthogonal linear trend
dat$julian.q <- t.poly.jul[, 2] # orthogonal quadratic trend

mod <- lm(count ~ year + julian.l + julian.q, data = dat )

summary(mod)
```

```{r}
par(mfrow = c(1, 2))
acf(resid(mod))
acf(resid(mod), type = "p")
```

### Autocorrelation

```{r}
mod <- gls(count ~ year + julian.l + julian.q, data = dat,
           correlation = corAR1())

summary(mod)
```

### Spatial Autocorrelation

```{r}
data("frogs")

frogs$year.z <- scale(frogs$year)
frogs$elevation.z <- scale(frogs$elevation)
frogs$waterarea[frogs$waterarea == 0 ] <- 0.25
frogs$waterarea.sqrt.l <- log(sqrt(frogs$waterarea))
frogs$waterarea.sqrt.l.z <- scale(frogs$waterarea.sqrt.l)

```

## Negative Binomial Model

```{r}

mod <- glm.nb(count2 ~ elevation.z + year.z + fish + vegetation + waterarea.sqrt.l.z + fish:vegetation, data = frogs)

par(mfrow=c(2, 2))
plot(mod)

spdata <- data.frame(resid = resid(mod), x = frogs$x, y = frogs$y)
coordinates(spdata) <- c("x", "y")
bubble(spdata, "resid", col = c("blue", "orange"), main = "Residuals",
       xlab = "X-coordinates", ylab = "Y-coordinates")
```

```{r}
vario.mod <- variogram(resid(mod) ~ 1, spdata)
plot(vario.mod)
```

```{r}
vario.mod.6dir <- variogram(resid(mod) ~ 1, spdata, alpha = seq(0, 150, by = 30))
plot(vario.mod.6dir)
```

## Hetroscedasticity

```{r}
data(ellenberg)
dat <- ellenberg[complete.cases(ellenberg[c("Yi.g", "Water",
                                            "Species")]), ]
mod <- lm(log(Yi.g) ~ Water + Species + Water:Species, dat)
par(mfrow=c(1, 2))
plot(resid(mod) ~ Species, dat)
scatter.smooth(dat$Water, sqrt(abs(resid(mod))), xlab = "Water")
```

