---
title: ''
mainfont: Arial
fontsize: 12pt
documentclass: report
header-includes:
- \PassOptionsToPackage{table}{xcolor}
- \usepackage{caption}
- \usepackage{amssymb}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage[table]{xcolor}
- \usepackage{fancyhdr}
- \usepackage{boldline}
- \usepackage{tipa}
   \definecolor{headergrey}{HTML}{545454}
   \definecolor{msdblue}{HTML}{1C93D1}
   \pagestyle{fancy}
   \setlength\headheight{30pt}
   \rhead{\color{headergrey}\today}
   \fancyhead[L]{\color{headergrey}Moretz, Brandon}
   \fancyhead[C]{\Large\bfseries\color{headergrey}Pairs Trading}
   \rfoot{\color{headergrey}Chapter 6}
   \lfoot{\color{headergrey}}
   \fancyfoot[C]{\rmfamily\color{headergrey}Case Studies In Data Science}
geometry: left = 1cm, right = 1cm, top = 2cm, bottom = 3cm
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    fig_caption: yes
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
---


```{r knitr_setup, include = FALSE}

knitr::opts_chunk$set(
   echo = T, 
   eval = TRUE, 
   dev = 'png', 
   fig.width = 9, 
   fig.height = 4.5)

options(knitr.table.format = "latex")

```

```{r report_setup, message = FALSE, warning = FALSE, include = FALSE}

library(data.table, quietly = TRUE, warn.conflicts = FALSE)
library(dplyr, quietly = TRUE, warn.conflicts = FALSE)
library(ggthemes, quietly = TRUE, warn.conflicts = FALSE)
library(scales, quietly = TRUE, warn.conflicts = FALSE)

library(knitr, quietly = TRUE, warn.conflicts = FALSE)
library(kableExtra, quietly = TRUE, warn.conflicts = FALSE)
library(pander, quietly = TRUE, warn.conflicts = FALSE)
library(formattable, quietly = TRUE, warn.conflicts = FALSE)

library(grid, quietly = TRUE, warn.conflicts = FALSE)
library(gridExtra, quietly = TRUE, warn.conflicts = FALSE)
library(extrafont, quietly = TRUE, warn.conflicts = FALSE)
library(tinytex, quietly = TRUE, warn.conflicts = FALSE)

library(here, quietly = TRUE, warn.conflicts = FALSE)

library(lattice, quietly = TRUE, warn.conflicts = FALSE)

library(quantmod, quietly = TRUE, warn.conflicts = FALSE)

options(tinytex.verbose = TRUE)
suppressMessages(library("tidyverse"))

pretty_kable <- function(data, title, dig = 2) {
  kable(data, caption = title, digits = dig) %>%
    kable_styling(bootstrap_options = c("striped", "hover")) %>%
      kableExtra::kable_styling(latex_options = "hold_position")
}

theme_set(theme_light())

# Theme Overrides
theme_update(axis.text.x = element_text(size = 10),
             axis.text.y = element_text(size = 10),
             plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "darkgreen"),
             axis.title = element_text(face = "bold", size = 12, colour = "steelblue4"),
             plot.subtitle = element_text(face = "bold", size = 8, colour = "darkred"),
             legend.title = element_text(size = 12, color = "darkred", face = "bold"),
             legend.position = "right", legend.title.align=0.5,
             panel.border = element_rect(linetype = "solid", 
                                         colour = "lightgray"), 
             plot.margin = unit(c( 0.1, 0.1, 0.1, 0.1), "inches"))

data_dir <- file.path(here::here(), "Case Studies", "datasets", "pairs_trading")

```

```{r pander_setup, include = FALSE}

knitr::opts_chunk$set(comment = NA)

panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)

```

# Pairs Trading

## Our Financial Data

```{r read-data}

readData <- 
   #
   # A function to read the data and convert the Date column to
   # an object of class Date.
   # The date values are expected to be in a column named Date.
   # We may want to relax this and allow the caller specify the 
   # column - by name or index.
   function(fileName, dateFormat = c("%Y-%m-%d", "%Y/%m/%d"), ...)
   {
      data <- read.csv(fileName, header = T,
                       stringsAsFactors = F, ...)
      for(fmt in dateFormat) {
         tmp <- as.Date(data$Date, fmt)
         if(all(!is.na(tmp))) {
            data$Date <- tmp
            break
         }
      }
      
      data[ ordered(data$Date), ]
   }

```

```{r get-symbols}

getSymbols("T", src = "yahoo", from = "1985-01-01", to = "2015-12-31")
getSymbols("VZ", src = "yahoo", from = "1985-01-01", to = "2015-12-31")
```


```{r plot-symbols, fig.height=4}

chartSeries(T)
chartSeries(VZ)
```

```{r}
ATT_adj = T$T.Adjusted; VER_adj <- VZ$VZ.Adjusted
```

```{r combine-stocks}

combineStocks <- 
   function(lseries, rseries, 
            stockNames = c(deparse(substitute((a)),
                           deparse(substitute(b)))),
            add_ratio = T) {
   l_adj <- lseries[, 6]; r_adj <- rseries[, 6]
   combined <- merge(l_adj, r_adj)
   
   df_result <- structure(data.table(Date = index(combined), combined),
             names = c("Date", stockNames))
   
   if(add_ratio) {
      
      Ratio <- combined[, 1] / combined[, 2]
      df_result <- cbind(df_result, Ratio)
      colnames(df_result)[4] <- "Ratio"
   }
   
   df_result
}

```

```{r get-overlap}

overlap <- combineStocks(T, VZ, c("ATT", "VER"))

names(overlap)

range(overlap$Date)
```

```{r plot-ratio}

plotRatio <-
   function(r, k = 1, date = seq(along = r), ...)
   {
      plot(date, r, type = "l", ...)
      
      mu <- mean(r); kval <- k * sd(r)
      upper <- mu + kval; lower <- mu - kval
      
      abline(h = c(mu,
                   upper,
                   lower),
             col = c("darkgreen", rep("red", 2 * length(k))),
             lty = "dashed")
      text(1, upper, upper)
   }


plotRatio(overlap$Ratio, k = .85, 
          overlap$Date, col = "lightgray",
          xlab = "Date", ylab = "Ratio")

```

```{r find-positions}

findNextPosition <-
   # e.g., findNextPosition(r)
   #     findNextPosition(r, 1774)
   # Check they are increasing and correctly offset
   function(ratio, startDay = 1, k = 1,
            m = mean(ratio), s = sd(ratio))
   {
      up = m + k * s
      down = m - k * s
      
      if(startDay > 1)
           ratio = ratio[ - (1:(startDay-1)) ]
      
     isExtreme = ratio >= up | ratio <= down
     
     if( is.na(isExtreme) || !any(isExtreme))
         return(integer())
      
      start = which(isExtreme)[1]
      backToNormal <- if(ratio[start] > up)
         ratio[ - (1:start) ] <= m
      else
         ratio[ - (1:start) ] >= m
      
      # return either the end of the position or the index
      # of the end of the vector
      # could return NA for not ended, i.e,, which(backToNormal)[1]
      # for both cases. But then the caller has to interpret that.
      
      end <- if(any(backToNormal))
               which(backToNormal)[1] + start
             else
                length(ratio)
      
      c(start, end) + startDay + 1
   }


r <- overlap$Ratio; k <- .85

a <- findNextPosition(r, k = k)
b <- findNextPosition(r, a[2], k = k)
c <- findNextPosition(r, b[2], k = k)


```

### Displaying the Positions

```{r show-position}

showPosition <- 
   function(days, ratios, radius = 100) {
      symbols(days, ratios, circles = rep(radius, 2),
              fg = c("darkgreen", "red"), add = T, inches = F)
   }

showPosition <- 
   function(pos, col = c("darkgreen", "red"), ...)
   {
      if(!is.list(pos))
         return(invisible(lapply(pos, showPosition, col = col, ...)))
      
      abline(v = pos, col = col, ...)
   }


```


```{r plot-ratio-2}

plotRatio(r, k, overlap$Date, xlab = "Date", ylab = "Ratio")

#showPosition(overlap$Date[a], r[a])
#showPosition(overlap$Date[b], r[b])
#showPosition(overlap$Date[c], r[c])
```

### Finding all Positions

```{r get-positions}

getPositions <-
   function(ratio, k = 1, m = mean(ratio), s = sd(ratio))
   {
      when = list()
      cur = 1
      
      while(cur < length(ratio)) {
         tmp <- findNextPosition(ratio, cur, k, m, s)
         if(length(tmp) == 0)
            break
         
         when[[length(when) + 1]] <- tmp
         if(is.na(tmp[2] || temp[2] == length(ratio)))
            break
         cur = tmp[2]
      }
      
      when
   }
```

```{r}
showPosition <-
   function(days, ratio, radius = 70)
   {
      if(is.list(days))
         days <- unlist(days)
      
      symbols(days, ratio[days],
              circles = rep(radius, length(days)),
              fg = c("darkgreen", "red"),
              add = T, inches = F)
   }
```

```{r}
k <- .5
pos <- getPositions(r, k)
plotRatio(r, k, col = "lightgray", ylab = "ratio")
showPosition(pos, r)
```

### Computing Profit

```{r}

positionProfit <-
   # r = overlap$att / overlap$verizon
   # k = 1.7
   # pos = getPositions(r, k)
   # positionProfile(pos[[1]], overlap$att, overlap$verizon)
   function(pos, stockPriceA, stockPriceB,
            ratioMean = mean(stockPriceA / stockPriceB ),
            p = 0.001, byStock = F)
   {
      if(is.list(pos)) {
         ans = sapply(pos, positionProfit,
                      stockPriceA, stockPriceB, ratioMean, p, byStock)
         
         if(byStock)
            rownames(ans) <- c("A", "B", "commission")
         
         return(ans)
      }
      
      # prices at the start and end of the positions
      priceA <- stockPriceA[pos]
      priceB <- stockPriceB[pos]
      
      # how many units can we by of A and B with $1?
      
      unitsOfA <- 1/priceA[1]
      unitsOfB <- 1/priceB[1]
      
      # The dollar amount of how many units we would buy of A and B
      # at the cost at the end of the position of each
      amt <- c(unitsOfA * priceA[2], unitsOfB * priceB[2])
      
      if(is.na(priceA[1]) | is.na(priceB[1]))
         return(0)
      
      # which are we selling
      sellWhat <- if(priceA[1] / priceB[1] > ratioMean) "A" else "B"
      
      profit <- if(sellWhat == "A")
                  c( ( 1 - amt[1]), (amt[2] - 1), - p * sum(amt))
               else
                  c( (1 - amt[2]), (amt[1] - 1), - p * sum(amt))
      
      if( byStock )
         profit
      else
         sum(profit)
   }

```

```{r}
pf <- positionProfit(c(1, 2), c(3838.48, 8712.87),
                              c(459.11, 1100.65), p = 0)

prof <- positionProfit(pos, overlap$ATT, overlap$VER, mean(r))
```

### Finding Optimal K

```{r}
i <- 1:floor(nrow(overlap)/2)
train <- overlap[i, ]
test <- overlap[ -i, ]

r.train <- train$Ratio
r.test <- test$Ratio

period <- seq(min(overlap$Date), by = "5 years", length = 2)
period.train <- paste(period[1], period[2], sep="/")

att.train <- T[period.train]$T.Adjusted
verizon.train <- VZ[period.train]$VZ.Adjusted
r.train <- att.train/verizon.train

period.test <- paste(period[2], max(overlap$Date), sep="/")
att.test <- T[period.test]$T.Adjusted
verizon.test <- VZ[period.test]$VZ.Adjusted
r.test <- att.test/verizon.test

k.max <- max((r.train - mean(r.train)) / sd(r.train))
k.min <- min((abs(r.train - mean(r.train)) / sd(r.train)))

ks <- seq(k.min, k.max, length = 1000)
m <- mean(r.train)

profits <-
   sapply(ks,
          function(k) {
             pos <- getPositions(r.train, k)
             sum(positionProfit(pos, train$ATT, train$VER,
                                mean(r.train)))
          })

plot(ks, profits, type = "l", xlab = "k", ylab = "Profit")

max_profits <- which.max(profits)
optimal <- ks[ max_profits ]

```

```{r}
tmp.k <- ks[ profits == max(profits) ]
pos <- getPositions(r.train, tmp.k[1])
all(sapply(tmp.k[-1],
           function(k)
              identical(pos, getPositions(r.train, k))))

k.star <- mean( ks[ profits == max(profits)])

pos <- getPositions(r.test, k.star, mean(r.train), sd(r.train))
testProfit <- sum(positionProfit(pos, test$ATT, test$VER), na.rm=T)

testProfit * 100

```

## Simulation

Vector Auto-regression

$X_t^{(1)} = \rho X^{(1)}_{t-1} + \psi(1 - \rho)X^{(2)}_{t-1} + \epsilon^{(1)}_t$

$X_t^{(2)} = \rho X^{(2)}_{t-1} + \psi(1 - \rho)X^{(1)}_{t-1}+ \epsilon^{(2)}_t$

$\epsilon^{(1)}_t \sim N(0, \sigma^2_i)$

...

$Y^{(1)}_t = \beta^{(1)}_0 + \beta^{(1)}_1t + X^{1}_t$

$Y^{(2)}_t = \beta^{(2)}_0 + \beta^{(2)}_1t + X^{2}_t$

### Simulating the Stock Price Series

```{r}
stockSim <-
   function(n = 4000, rho = 0.99, psi = 0, sigma = rep(1, 2),
            beta0 = rep(100, 2), beta1 = rep(0, 2),
            epsilon = matrix(rnorm(2*n, sd = sigma),
                             nrow = n, byrow = T))
   {
      X <- matrix(0, nrow = n, ncol = 2)
      X[1, ] <- epsilon[1, ]
      
      A <- matrix(c(rho, psi * (1-rho), psi*(1-rho), rho), nrow = 2)
      for(i in 2:n)
         X[i, ] = A %*% X[i-1, ] + epsilon[i, ]
      
      X[, 1] <- beta0[1] + beta1[1] * (1:n) + X[, 1]
      X[, 2] <- beta0[2] + beta1[2] * (1:n) + X[, 2]
      
      X
   }

```

```{r}
a <- stockSim(rho = .99, psi = 0)

matplot(1:nrow(a), a, type = "l", xlab = "Day", ylab = "Y",
        col = c("black", "grey"), lty = "solid")


beta1 <- c(.05, .1)

a <- stockSim(beta1 = c(.05, .1))

matplot(1:nrow(a), a, type = "l", xlab = "Day", ylab = "Y",
        col = c("black", "grey"), lty = "solid")

```

### Simulation Utilities

```{r}

runSim <-
function(rho = .99, psi = .9, beta0 = c(100, 100), beta1 = c(0, 0),
         sigma = c(1, 1), n = 4000)
{
    X = stockSim(n, rho, psi, sigma, beta = beta0, beta1 = beta1)
    train = X[ 1:floor(n/2), ]
    test = X[ (floor(n/2)+1):n, ]
    m = mean(train[, 1]/train[, 2])
    s = sd(train[, 1]/train[, 2])
    k.star = getBestK(train[, 1], train[, 2], m = m, s = s)
    getProfit.K(k.star, test[, 1], test[, 2], m, s)
}

getProfit.K =
function(k, x, y, m = mean(x/y), s = sd(x/y))
{
    pos = getPositions(x/y, k, m = m, s = s)
    if(length(pos) == 0)  
       0
    else
       sum(positionProfit(pos, x, y, m), na.rm=T)
}

getBestK = 
function(x, y, ks = seq(0.1, max.k, length = N), N = 100, 
         max.k = NA, m = mean(x/y), s = sd(x/y))
{
    if(is.na(max.k)) {
       r = x/y
       max.k = max(r/sd(r))
    }

    pr.k = sapply(ks, getProfit.K, x, y, m = m, s = s)
    median(ks[ pr.k == max(pr.k) ])
}

simProfitDist = 
function(..., B = 999) 
      sapply(1:B,  function(i, ...) runSim(...), ...)

```

### Run the Simulation

```{r}
system.time({ x = simProfitDist( .99, .9, c(0, 0)) })

ggplot(data.table(profit = x), aes(profit)) +
   geom_density()
```

```{r}
g <- expand.grid(psi = seq(.8, .99, length.out = 20),
                 beta1 = seq(-0.01, .01, length.out = 20),
                 beta2 = seq(-0.1, 0.01, length.out = 20))

dim(g)
```

```{r}
Rprof("sim.prof")

system.time({x = simProfitDist( .99, .9, c(0, 0))})

Rprof(NULL)

head(summaryRprof("sim.prof")$by.self)
```

```{r}
counter <- 0L
trace(findNextPosition, quote( counter <<- counter + 1L),
      print = FALSE)

system.time({x = simProfitDist( .99, .9, c(0, 0))})

counter

untrace(findNextPosition)
```

```{r}
library(compiler)
stockSim.cmp <- cmpfun(stockSim)

```

```{r}

tm.orig <- system.time({replicate(80, stockSim())})
tm.compiled <- system.time({replicate(80, stockSim.cmp())})

tm.orig/tm.compiled
```

```{r}
c.lib <- paste(here(), "Case Studies", "06_stockSim.dll", sep="/")

dyn.load(c.lib)
```

```{r}
stockSim.c <-
   function(n = 4000, rho = 0.99, psi = 0, sigma = rep(1, 2),
            beta0 = rep(100, 2), beta1 = rep(0, 2),
            epsilon = matrix(rnorm(2*n, sd = sigma), nrow = n))
   {
      X <- matrix(0, nrow = n, ncol = 2)
      X[1, ] <- epsilon[1, ]
      
      X <- .C("stockSim", X, as.integer(n), rho, psi, epsilon)[[1]]
      
      X[, 1] <- beta0[1] + beta1[1] + (1:n) + X[, 1]
      X[, 2] <- beta0[2] + beta1[2] + (1:n) + X[, 2]
      
      X
   }
```


```{r}

e <- matrix(rnorm(2*4000, sd = c(1, 1)), , 2)
tmp1 <- stockSim.c(epsilon = e)
tmp2 <- stockSim(epsilon = e)

```

```{r}

stockSim <- stockSim.c

Rprof("sim.prof")
system.time({x = simProfitDist(.99, .9, c(0, 0))})
Rprof(NULL)
head(summaryRprof("sim.prof")$by.self)
```

